import type { Manifest } from "@zyra/core";

export const MOCK_MANIFEST: Manifest = {
  version: "1.0",
  stages: [
    {
      stage: "control",
      command: "string",
      label: "String",
      description: "A string constant to feed into other nodes",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["string"] }],
      args: [
        {
          key: "value",
          label: "Value",
          type: "string",
          required: true,
          placeholder: "hello world",
          description: "String value",
        },
      ],
    },
    {
      stage: "control",
      command: "number",
      label: "Number",
      description: "A numeric constant to feed into other nodes",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["number"] }],
      args: [
        {
          key: "value",
          label: "Value",
          type: "number",
          required: true,
          placeholder: "0",
          description: "Numeric value",
        },
      ],
    },
    {
      stage: "control",
      command: "boolean",
      label: "Boolean",
      description: "A true/false toggle to feed into other nodes",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["boolean"] }],
      args: [
        {
          key: "value",
          label: "Value",
          type: "boolean",
          required: true,
          default: false,
          description: "Boolean value",
        },
      ],
    },
    {
      stage: "control",
      command: "choice",
      label: "Choice",
      description: "Pick one option from a user-defined list",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [
        { id: "value", label: "Value", types: ["string"] },
        { id: "label", label: "Label", types: ["string"] },
      ],
      args: [
        {
          key: "options",
          label: "Options",
          type: "string",
          required: true,
          placeholder: "[]",
          description: "List of {label, value} choices (managed by visual editor)",
        },
        {
          key: "value",
          label: "Selected",
          type: "string",
          required: true,
          placeholder: "a",
          description: "The chosen value",
        },
      ],
    },
    {
      stage: "control",
      command: "filepath",
      label: "File Path",
      description: "A file path constant to feed into other nodes",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["filepath"] }],
      args: [
        {
          key: "value",
          label: "Path",
          type: "filepath",
          required: true,
          placeholder: "/data/input.nc",
          description: "File path value",
        },
      ],
    },
    {
      stage: "control",
      command: "date",
      label: "Date",
      description: "Pick a date or date range with an optional period",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [
        { id: "start_date", label: "Start Date", types: ["date", "string"] },
        { id: "end_date", label: "End Date", types: ["date", "string"] },
        { id: "period", label: "Period", types: ["string"] },
      ],
      args: [
        {
          key: "start_date",
          label: "Start Date",
          type: "date",
          required: true,
          placeholder: "2025-01-01",
          description: "Start date (YYYY-MM-DD)",
        },
        {
          key: "end_date",
          label: "End Date",
          type: "date",
          required: false,
          placeholder: "2025-12-31",
          description: "End date (YYYY-MM-DD). Leave empty for a single date.",
        },
        {
          key: "period",
          label: "Period",
          type: "enum",
          options: ["daily", "weekly", "monthly", "yearly", "custom"],
          required: false,
          description: "Repeat interval between start and end dates",
        },
        {
          key: "custom_period",
          label: "Custom Period",
          type: "string",
          required: false,
          placeholder: "P1M15D",
          description: "ISO 8601 duration (e.g. P1D, P2W, P1M, P1Y, P1M15D, PT12H)",
        },
      ],
    },
    {
      stage: "control",
      command: "secret",
      label: "Secret",
      description: "A secret value (API key, password) stored as an environment variable",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["string"] }],
      args: [
        {
          key: "name",
          label: "Name",
          type: "string",
          required: true,
          placeholder: "API_KEY",
          description: "Environment variable name (used as ${NAME} in pipeline)",
        },
        {
          key: "value",
          label: "Value",
          type: "string",
          required: true,
          placeholder: "••••••••",
          description: "Secret value (never written to pipeline YAML)",
        },
        {
          key: "description",
          label: "Description",
          type: "string",
          required: false,
          placeholder: "API key for external service",
          description: "Optional description of what this secret is for",
        },
      ],
    },
    {
      stage: "control",
      command: "cron",
      label: "Cron Schedule",
      description: "Define a recurring execution schedule using a cron expression",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "schedule", label: "Schedule", types: ["string"] }],
      args: [
        {
          key: "expression",
          label: "Cron Expression",
          type: "string",
          required: true,
          placeholder: "0 6 * * MON",
          description: "Standard cron expression (minute hour day month weekday)",
        },
        {
          key: "timezone",
          label: "Timezone",
          type: "string",
          required: false,
          placeholder: "UTC",
          description: "IANA timezone (e.g. America/New_York, UTC)",
        },
        {
          key: "enabled",
          label: "Enabled",
          type: "boolean",
          required: false,
          default: true,
          description: "Whether the schedule is active",
        },
      ],
    },
    {
      stage: "control",
      command: "delay",
      label: "Delay / Throttle",
      description: "Insert a configurable wait before downstream stages (e.g. to respect API rate limits)",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "delay", label: "Delay", types: ["number", "string"] }],
      args: [
        {
          key: "duration",
          label: "Duration",
          type: "number",
          required: true,
          placeholder: "5",
          description: "How long to wait before running the downstream stage",
        },
        {
          key: "unit",
          label: "Unit",
          type: "enum",
          options: ["seconds", "minutes", "hours"],
          required: true,
          default: "seconds",
          description: "Time unit for the delay duration",
        },
        {
          key: "jitter",
          label: "Random Jitter",
          type: "number",
          required: false,
          placeholder: "0",
          description: "Add random jitter up to this many seconds to avoid thundering herd (not yet implemented — ignored at execution time)",
        },
      ],
    },
    {
      stage: "control",
      command: "conditional",
      label: "Conditional",
      description: "Route data down different paths based on a condition",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [
        { id: "input", label: "Input", types: ["any"] },
      ],
      outputs: [
        { id: "true", label: "True", types: ["any"] },
        { id: "false", label: "False", types: ["any"] },
      ],
      args: [
        {
          key: "field",
          label: "Field",
          type: "string",
          required: true,
          placeholder: "file_size",
          description: "The field or property to evaluate",
        },
        {
          key: "operator",
          label: "Operator",
          type: "enum",
          options: ["==", "!=", ">", "<", ">=", "<=", "contains", "matches"],
          required: true,
          description: "Comparison operator",
        },
        {
          key: "compare_value",
          label: "Compare Value",
          type: "string",
          required: true,
          placeholder: "100",
          description: "Value to compare against",
        },
      ],
    },
    {
      stage: "control",
      command: "loop",
      label: "Loop",
      description: "Iterate over a list of items, running downstream nodes for each",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [
        { id: "items", label: "Items", types: ["json", "any"] },
      ],
      outputs: [
        { id: "item", label: "Current Item", types: ["any"] },
        { id: "index", label: "Index", types: ["number"] },
        { id: "done", label: "Done", types: ["any"] },
      ],
      args: [
        {
          key: "mode",
          label: "Mode",
          type: "enum",
          options: ["each", "batch", "range"],
          required: true,
          description: "Iteration mode: each item, batched groups, or numeric range",
        },
        {
          key: "batch_size",
          label: "Batch Size",
          type: "number",
          required: false,
          placeholder: "10",
          description: "Number of items per batch (only for batch mode)",
        },
        {
          key: "range_start",
          label: "Range Start",
          type: "number",
          required: false,
          placeholder: "0",
          description: "Start of numeric range (only for range mode)",
        },
        {
          key: "range_end",
          label: "Range End",
          type: "number",
          required: false,
          placeholder: "100",
          description: "End of numeric range (only for range mode)",
        },
        {
          key: "range_step",
          label: "Step",
          type: "number",
          required: false,
          placeholder: "1",
          description: "Step size for range iteration",
        },
        {
          key: "max_parallel",
          label: "Max Parallel",
          type: "number",
          required: false,
          placeholder: "1",
          description: "Maximum concurrent iterations (1 = sequential)",
        },
      ],
    },
    {
      stage: "search",
      command: "catalog",
      label: "Catalog Search",
      description: "Search data catalogs for available datasets",
      cli: "zyra search catalog",
      status: "planned",
      color: "#0078D4",
      inputs: [],
      outputs: [{ id: "results", label: "Results", types: ["json"] }],
      args: [
        {
          key: "query",
          label: "Query",
          type: "string",
          required: true,
          placeholder: "temperature 2m",
          description: "Search query for data catalog",
        },
        {
          key: "provider",
          label: "Provider",
          type: "enum",
          options: ["noaa", "copernicus", "nasa"],
          required: false,
        },
      ],
    },
    {
      stage: "acquire",
      command: "http",
      label: "HTTP Acquire",
      description: "Download a file from an HTTP/HTTPS URL",
      cli: "zyra acquire http",
      status: "implemented",
      color: "#00529E",
      inputs: [],
      outputs: [{ id: "file", label: "File", types: ["any"] }],
      args: [
        {
          key: "url",
          label: "URL",
          type: "string",
          required: true,
          placeholder: "https://...",
          description: "Source URL to fetch",
        },
        {
          key: "output",
          flag: "-o",
          label: "Output Path",
          type: "filepath",
          required: true,
        },
      ],
    },
    {
      stage: "acquire",
      command: "s3",
      label: "S3 Acquire",
      description: "Download an object from an Amazon S3 bucket",
      cli: "zyra acquire s3",
      status: "implemented",
      color: "#00529E",
      inputs: [],
      outputs: [{ id: "file", label: "File", types: ["any"] }],
      args: [
        {
          key: "bucket",
          label: "Bucket",
          type: "string",
          required: true,
          description: "S3 bucket name",
        },
        {
          key: "key",
          label: "Object Key",
          type: "string",
          required: true,
        },
        {
          key: "output",
          flag: "-o",
          label: "Output Path",
          type: "filepath",
          required: true,
        },
      ],
    },
    {
      stage: "process",
      command: "convert-format",
      label: "Convert Format",
      description: "Convert between geospatial file formats",
      cli: "zyra process convert-format",
      status: "implemented",
      color: "#2C670C",
      inputs: [
        {
          id: "file",
          label: "Input File",
          types: ["grib2", "netcdf", "geotiff", "any"],
        },
      ],
      outputs: [
        {
          id: "file",
          label: "Output File",
          types: ["netcdf", "grib2", "geotiff"],
        },
      ],
      args: [
        {
          key: "format",
          label: "Target Format",
          type: "enum",
          options: ["netcdf", "grib2", "geotiff"],
          required: true,
        },
      ],
    },
    {
      stage: "process",
      command: "regrid",
      label: "Regrid",
      description: "Interpolate data onto a new grid resolution",
      cli: "zyra process regrid",
      status: "implemented",
      color: "#2C670C",
      inputs: [
        { id: "file", label: "Input File", types: ["netcdf", "grib2"] },
      ],
      outputs: [
        { id: "file", label: "Output File", types: ["netcdf", "grib2"] },
      ],
      args: [
        {
          key: "resolution",
          label: "Resolution",
          type: "string",
          required: true,
          placeholder: "0.25",
          description: "Target grid resolution in degrees",
        },
        {
          key: "method",
          label: "Method",
          type: "enum",
          options: ["bilinear", "nearest", "conservative"],
          required: false,
          default: "bilinear",
        },
      ],
    },
    {
      stage: "process",
      command: "subset",
      label: "Subset",
      description: "Extract a spatial or variable subset from a dataset",
      cli: "zyra process subset",
      status: "implemented",
      color: "#2C670C",
      inputs: [
        { id: "file", label: "Input File", types: ["netcdf", "grib2"] },
      ],
      outputs: [
        { id: "file", label: "Output File", types: ["netcdf", "grib2"] },
      ],
      args: [
        {
          key: "bbox",
          label: "Bounding Box",
          type: "string",
          required: false,
          placeholder: "lon_min,lat_min,lon_max,lat_max",
          description: "Spatial bounding box",
        },
        {
          key: "variables",
          label: "Variables",
          type: "string",
          required: false,
          placeholder: "temperature,pressure",
          description: "Comma-separated variable names",
        },
      ],
    },
    {
      stage: "visualize",
      command: "plot-map",
      label: "Plot Map",
      description: "Generate a map visualization of gridded data",
      cli: "zyra visualize plot-map",
      status: "implemented",
      color: "#7B2D8E",
      inputs: [
        { id: "file", label: "Input File", types: ["netcdf", "geotiff"] },
      ],
      outputs: [{ id: "image", label: "Image", types: ["png", "svg"] }],
      args: [
        {
          key: "variable",
          label: "Variable",
          type: "string",
          required: true,
          description: "Variable to plot",
        },
        {
          key: "colormap",
          label: "Colormap",
          type: "enum",
          options: ["viridis", "plasma", "inferno", "magma", "coolwarm"],
          required: false,
          default: "viridis",
        },
        {
          key: "output",
          flag: "-o",
          label: "Output Path",
          type: "filepath",
          required: true,
        },
      ],
    },
    {
      stage: "verify",
      command: "checksum",
      label: "Checksum",
      description: "Verify file integrity by computing and comparing checksums",
      cli: "zyra verify checksum",
      status: "planned",
      color: "#2E8B57",
      inputs: [{ id: "file", label: "File", types: ["any"] }],
      outputs: [{ id: "result", label: "Result", types: ["json"] }],
      args: [
        {
          key: "algorithm",
          label: "Algorithm",
          type: "enum",
          options: ["md5", "sha256", "sha512"],
          required: false,
          default: "sha256",
        },
        {
          key: "expected",
          label: "Expected Hash",
          type: "string",
          required: false,
          placeholder: "abc123...",
          description: "Expected checksum to compare against",
        },
      ],
    },
    {
      stage: "verify",
      command: "schema",
      label: "Schema Validate",
      description: "Validate dataset structure and variables against a schema",
      cli: "zyra verify schema",
      status: "planned",
      color: "#2E8B57",
      inputs: [
        { id: "file", label: "Input File", types: ["netcdf", "json", "any"] },
      ],
      outputs: [{ id: "report", label: "Report", types: ["json"] }],
      args: [
        {
          key: "schema",
          label: "Schema Path",
          type: "filepath",
          required: true,
          placeholder: "/schemas/my-schema.json",
          description: "Path to the validation schema",
        },
      ],
    },
    {
      stage: "export",
      command: "upload-s3",
      label: "Upload to S3",
      description: "Upload output files to an Amazon S3 bucket",
      cli: "zyra export upload-s3",
      status: "implemented",
      color: "#B8860B",
      inputs: [{ id: "file", label: "File", types: ["any"] }],
      outputs: [],
      args: [
        {
          key: "bucket",
          label: "Bucket",
          type: "string",
          required: true,
        },
        {
          key: "prefix",
          label: "Key Prefix",
          type: "string",
          required: false,
          placeholder: "output/",
        },
      ],
    },
  ],
};
