import type { Manifest } from "@zyra/core";

export const MOCK_MANIFEST: Manifest = {
  version: "1.0",
  stages: [
    {
      stage: "control",
      command: "variable",
      label: "Variable",
      description: "Define a named variable to pass values into the pipeline",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["any"] }],
      args: [
        {
          key: "name",
          label: "Name",
          type: "string",
          required: true,
          placeholder: "my_var",
          description: "Variable name",
        },
        {
          key: "value",
          label: "Value",
          type: "string",
          required: true,
          placeholder: "...",
          description: "The value to pass downstream",
        },
      ],
    },
    {
      stage: "control",
      command: "string",
      label: "String",
      description: "A string constant to feed into other nodes",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["string"] }],
      args: [
        {
          key: "value",
          label: "Value",
          type: "string",
          required: true,
          placeholder: "hello world",
          description: "String value",
        },
      ],
    },
    {
      stage: "control",
      command: "number",
      label: "Number",
      description: "A numeric constant to feed into other nodes",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["number"] }],
      args: [
        {
          key: "value",
          label: "Value",
          type: "number",
          required: true,
          placeholder: "0",
          description: "Numeric value",
        },
      ],
    },
    {
      stage: "control",
      command: "boolean",
      label: "Boolean",
      description: "A true/false toggle to feed into other nodes",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["boolean"] }],
      args: [
        {
          key: "value",
          label: "Value",
          type: "boolean",
          required: true,
          default: false,
          description: "Boolean value",
        },
      ],
    },
    {
      stage: "control",
      command: "choice",
      label: "Choice",
      description: "Pick one option from a user-defined list",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["string"] }],
      args: [
        {
          key: "options",
          label: "Options",
          type: "string",
          required: true,
          placeholder: "a,b,c",
          description: "Comma-separated list of choices",
        },
        {
          key: "value",
          label: "Selected",
          type: "string",
          required: true,
          placeholder: "a",
          description: "The chosen value",
        },
      ],
    },
    {
      stage: "control",
      command: "filepath",
      label: "File Path",
      description: "A file path constant to feed into other nodes",
      cli: "",
      status: "implemented",
      color: "#888888",
      inputs: [],
      outputs: [{ id: "value", label: "Value", types: ["filepath"] }],
      args: [
        {
          key: "value",
          label: "Path",
          type: "filepath",
          required: true,
          placeholder: "/data/input.nc",
          description: "File path value",
        },
      ],
    },
    {
      stage: "search",
      command: "catalog",
      label: "Catalog Search",
      description: "Search data catalogs for available datasets",
      cli: "zyra search catalog",
      status: "planned",
      color: "#0078D4",
      inputs: [],
      outputs: [{ id: "results", label: "Results", types: ["json"] }],
      args: [
        {
          key: "query",
          label: "Query",
          type: "string",
          required: true,
          placeholder: "temperature 2m",
          description: "Search query for data catalog",
        },
        {
          key: "provider",
          label: "Provider",
          type: "enum",
          options: ["noaa", "copernicus", "nasa"],
          required: false,
        },
      ],
    },
    {
      stage: "acquire",
      command: "http",
      label: "HTTP Acquire",
      description: "Download a file from an HTTP/HTTPS URL",
      cli: "zyra acquire http",
      status: "implemented",
      color: "#00529E",
      inputs: [],
      outputs: [{ id: "file", label: "File", types: ["any"] }],
      args: [
        {
          key: "url",
          label: "URL",
          type: "string",
          required: true,
          placeholder: "https://...",
          description: "Source URL to fetch",
        },
        {
          key: "output",
          flag: "-o",
          label: "Output Path",
          type: "filepath",
          required: true,
        },
      ],
    },
    {
      stage: "acquire",
      command: "s3",
      label: "S3 Acquire",
      description: "Download an object from an Amazon S3 bucket",
      cli: "zyra acquire s3",
      status: "implemented",
      color: "#00529E",
      inputs: [],
      outputs: [{ id: "file", label: "File", types: ["any"] }],
      args: [
        {
          key: "bucket",
          label: "Bucket",
          type: "string",
          required: true,
          description: "S3 bucket name",
        },
        {
          key: "key",
          label: "Object Key",
          type: "string",
          required: true,
        },
        {
          key: "output",
          flag: "-o",
          label: "Output Path",
          type: "filepath",
          required: true,
        },
      ],
    },
    {
      stage: "process",
      command: "convert-format",
      label: "Convert Format",
      description: "Convert between geospatial file formats",
      cli: "zyra process convert-format",
      status: "implemented",
      color: "#2C670C",
      inputs: [
        {
          id: "file",
          label: "Input File",
          types: ["grib2", "netcdf", "geotiff", "any"],
        },
      ],
      outputs: [
        {
          id: "file",
          label: "Output File",
          types: ["netcdf", "grib2", "geotiff"],
        },
      ],
      args: [
        {
          key: "format",
          label: "Target Format",
          type: "enum",
          options: ["netcdf", "grib2", "geotiff"],
          required: true,
        },
      ],
    },
    {
      stage: "process",
      command: "regrid",
      label: "Regrid",
      description: "Interpolate data onto a new grid resolution",
      cli: "zyra process regrid",
      status: "implemented",
      color: "#2C670C",
      inputs: [
        { id: "file", label: "Input File", types: ["netcdf", "grib2"] },
      ],
      outputs: [
        { id: "file", label: "Output File", types: ["netcdf", "grib2"] },
      ],
      args: [
        {
          key: "resolution",
          label: "Resolution",
          type: "string",
          required: true,
          placeholder: "0.25",
          description: "Target grid resolution in degrees",
        },
        {
          key: "method",
          label: "Method",
          type: "enum",
          options: ["bilinear", "nearest", "conservative"],
          required: false,
          default: "bilinear",
        },
      ],
    },
    {
      stage: "process",
      command: "subset",
      label: "Subset",
      description: "Extract a spatial or variable subset from a dataset",
      cli: "zyra process subset",
      status: "implemented",
      color: "#2C670C",
      inputs: [
        { id: "file", label: "Input File", types: ["netcdf", "grib2"] },
      ],
      outputs: [
        { id: "file", label: "Output File", types: ["netcdf", "grib2"] },
      ],
      args: [
        {
          key: "bbox",
          label: "Bounding Box",
          type: "string",
          required: false,
          placeholder: "lon_min,lat_min,lon_max,lat_max",
          description: "Spatial bounding box",
        },
        {
          key: "variables",
          label: "Variables",
          type: "string",
          required: false,
          placeholder: "temperature,pressure",
          description: "Comma-separated variable names",
        },
      ],
    },
    {
      stage: "visualize",
      command: "plot-map",
      label: "Plot Map",
      description: "Generate a map visualization of gridded data",
      cli: "zyra visualize plot-map",
      status: "implemented",
      color: "#7B2D8E",
      inputs: [
        { id: "file", label: "Input File", types: ["netcdf", "geotiff"] },
      ],
      outputs: [{ id: "image", label: "Image", types: ["png", "svg"] }],
      args: [
        {
          key: "variable",
          label: "Variable",
          type: "string",
          required: true,
          description: "Variable to plot",
        },
        {
          key: "colormap",
          label: "Colormap",
          type: "enum",
          options: ["viridis", "plasma", "inferno", "magma", "coolwarm"],
          required: false,
          default: "viridis",
        },
        {
          key: "output",
          flag: "-o",
          label: "Output Path",
          type: "filepath",
          required: true,
        },
      ],
    },
    {
      stage: "export",
      command: "upload-s3",
      label: "Upload to S3",
      description: "Upload output files to an Amazon S3 bucket",
      cli: "zyra export upload-s3",
      status: "implemented",
      color: "#B8860B",
      inputs: [{ id: "file", label: "File", types: ["any"] }],
      outputs: [],
      args: [
        {
          key: "bucket",
          label: "Bucket",
          type: "string",
          required: true,
        },
        {
          key: "prefix",
          label: "Key Prefix",
          type: "string",
          required: false,
          placeholder: "output/",
        },
      ],
    },
  ],
};
